package Blah;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author acer
 */
public class RagFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public RagFrame() {
        initComponents();
        //Dimension jFrameDivSize = new Dimension(1000, 600);
        // Dimension topBarDivSize = new Dimension(1000, 40);
        //this.setSize(jFrameDivSize);
        this.setLocationRelativeTo(null);
        this.setResizable(true);
        this.setVisible(true);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25));
       
        jframeCustmize();
         setMenuLabelImageIcons();
    }

    protected void paintComponent(Graphics g) {

    }

    private void jframeCustmize() {
        closeLabel.setIcon(labelSetIcon("/Icons/close.png", closeLabel.getWidth() - 20, closeLabel.getHeight() - 20));
        boxLabel.setIcon(labelSetIcon("/Icons/square.png", boxLabel.getWidth() - 12, boxLabel.getHeight() - 14));
        miniLabel.setIcon(labelSetIcon("/Icons/minus.png", miniLabel.getWidth() - 8, miniLabel.getHeight() - 8));

        miniLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setState(JFrame.ICONIFIED);
            }
        });
    }

    public void setMenuLabelImageIcons() {
        JLabel[] lb = {m1, m2, m3, m4, m5, m6, m7, m8};
        for (int i = 0; i < lb.length; i++) {
            lb[i].setIcon(labelSetIcon("/optionsIcons/data.png", closeLabel.getWidth() - 10, closeLabel.getHeight() - 10));
        }
    }

    public ImageIcon labelSetIcon(String src, int w, int h) {
        ImageSizer imgSizer = new ImageSizer();
        ImageIcon i = imgSizer.overaallResizer(src, w, h);
        return i;
    }

    public void setTitleBarEvent() {

    }

    public void logoutButtonEvent(java.awt.event.ActionEvent ev) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jToggleButton1 = new javax.swing.JToggleButton();
                roundedPanel1 = new RoundedPanel();
                roundedPanel2 = new RoundedPanel();
                jPanel1 = new javax.swing.JPanel();
                closeLabel = new javax.swing.JLabel();
                miniLabel = new javax.swing.JLabel();
                boxLabel = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tableDark1 = new TableDark();
                jPanel3 = new javax.swing.JPanel();
                roundedPanel3 = new RoundedPanel();
                m1 = new javax.swing.JLabel();
                roundedPanel4 = new RoundedPanel();
                m2 = new javax.swing.JLabel();
                roundedPanel5 = new RoundedPanel();
                m3 = new javax.swing.JLabel();
                roundedPanel7 = new RoundedPanel();
                m4 = new javax.swing.JLabel();
                roundedPanel6 = new RoundedPanel();
                m5 = new javax.swing.JLabel();
                roundedPanel8 = new RoundedPanel();
                m6 = new javax.swing.JLabel();
                roundedPanel9 = new RoundedPanel();
                m7 = new javax.swing.JLabel();
                roundedPanel10 = new RoundedPanel();
                m8 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();

                jToggleButton1.setText("jToggleButton1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);

                roundedPanel1.setBackground(new java.awt.Color(153, 153, 153));
                roundedPanel1.setRoundBottomLeft(25);
                roundedPanel1.setRoundBottomRight(25);
                roundedPanel1.setRoundTopLeft(25);
                roundedPanel1.setRoundTopRight(25);

                roundedPanel2.setBackground(new java.awt.Color(51, 51, 51));
                roundedPanel2.setRoundTopLeft(25);
                roundedPanel2.setRoundTopRight(25);
                roundedPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseDragged(java.awt.event.MouseEvent evt) {
                                roundedPanel2MouseDragged(evt);
                        }
                });
                roundedPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                roundedPanel2MousePressed(evt);
                        }
                });

                jPanel1.setOpaque(false);
                jPanel1.setPreferredSize(new java.awt.Dimension(120, 25));
                jPanel1.setLayout(new java.awt.BorderLayout());

                closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                closeLabel.setPreferredSize(new java.awt.Dimension(40, 25));
                closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                closeLabelMouseClicked(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                closeLabelMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                closeLabelMouseExited(evt);
                        }
                });
                jPanel1.add(closeLabel, java.awt.BorderLayout.LINE_END);

                miniLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                miniLabel.setPreferredSize(new java.awt.Dimension(40, 25));
                miniLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                miniLabelMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                miniLabelMouseExited(evt);
                        }
                });
                jPanel1.add(miniLabel, java.awt.BorderLayout.WEST);

                boxLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                boxLabel.setPreferredSize(new java.awt.Dimension(40, 25));
                jPanel1.add(boxLabel, java.awt.BorderLayout.CENTER);

                jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("RAG");
                jLabel1.setToolTipText("");

                javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
                roundedPanel2.setLayout(roundedPanel2Layout);
                roundedPanel2Layout.setHorizontalGroup(
                        roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                roundedPanel2Layout.setVerticalGroup(
                        roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                );

                jPanel2.setOpaque(false);

                tableDark1.setBackground(new java.awt.Color(255, 51, 153));
                tableDark1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null},
                                {null, null, null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
                        }
                ));
                jScrollPane1.setViewportView(tableDark1);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
                jPanel3.setOpaque(false);
                jPanel3.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

                roundedPanel3.setBackground(new java.awt.Color(51, 51, 51));
                roundedPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                roundedPanel3.setRoundBottomLeft(5);
                roundedPanel3.setRoundBottomRight(5);
                roundedPanel3.setRoundTopLeft(5);
                roundedPanel3.setRoundTopRight(5);
                roundedPanel3.setLayout(new java.awt.BorderLayout());

                m1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                roundedPanel3.add(m1, java.awt.BorderLayout.CENTER);

                jPanel3.add(roundedPanel3);

                roundedPanel4.setBackground(new java.awt.Color(51, 51, 51));
                roundedPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                roundedPanel4.setRoundBottomLeft(5);
                roundedPanel4.setRoundBottomRight(5);
                roundedPanel4.setRoundTopLeft(5);
                roundedPanel4.setRoundTopRight(5);
                roundedPanel4.setLayout(new java.awt.BorderLayout());

                m2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                roundedPanel4.add(m2, java.awt.BorderLayout.CENTER);

                jPanel3.add(roundedPanel4);

                roundedPanel5.setBackground(new java.awt.Color(51, 51, 51));
                roundedPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                roundedPanel5.setRoundBottomLeft(5);
                roundedPanel5.setRoundBottomRight(5);
                roundedPanel5.setRoundTopLeft(5);
                roundedPanel5.setRoundTopRight(5);
                roundedPanel5.setLayout(new java.awt.BorderLayout());

                m3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                roundedPanel5.add(m3, java.awt.BorderLayout.CENTER);

                jPanel3.add(roundedPanel5);

                roundedPanel7.setBackground(new java.awt.Color(51, 51, 51));
                roundedPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                roundedPanel7.setRoundBottomLeft(5);
                roundedPanel7.setRoundBottomRight(5);
                roundedPanel7.setRoundTopLeft(5);
                roundedPanel7.setRoundTopRight(5);
                roundedPanel7.setLayout(new java.awt.BorderLayout());

                m4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                roundedPanel7.add(m4, java.awt.BorderLayout.CENTER);

                jPanel3.add(roundedPanel7);

                roundedPanel6.setBackground(new java.awt.Color(51, 51, 51));
                roundedPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                roundedPanel6.setRoundBottomLeft(5);
                roundedPanel6.setRoundBottomRight(5);
                roundedPanel6.setRoundTopLeft(5);
                roundedPanel6.setRoundTopRight(5);
                roundedPanel6.setLayout(new java.awt.BorderLayout());

                m5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                roundedPanel6.add(m5, java.awt.BorderLayout.CENTER);

                jPanel3.add(roundedPanel6);

                roundedPanel8.setBackground(new java.awt.Color(51, 51, 51));
                roundedPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                roundedPanel8.setRoundBottomLeft(5);
                roundedPanel8.setRoundBottomRight(5);
                roundedPanel8.setRoundTopLeft(5);
                roundedPanel8.setRoundTopRight(5);
                roundedPanel8.setLayout(new java.awt.BorderLayout());

                m6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                roundedPanel8.add(m6, java.awt.BorderLayout.CENTER);

                jPanel3.add(roundedPanel8);

                roundedPanel9.setBackground(new java.awt.Color(51, 51, 51));
                roundedPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                roundedPanel9.setRoundBottomLeft(5);
                roundedPanel9.setRoundBottomRight(5);
                roundedPanel9.setRoundTopLeft(5);
                roundedPanel9.setRoundTopRight(5);
                roundedPanel9.setLayout(new java.awt.BorderLayout());

                m7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                roundedPanel9.add(m7, java.awt.BorderLayout.CENTER);

                jPanel3.add(roundedPanel9);

                roundedPanel10.setBackground(new java.awt.Color(51, 51, 51));
                roundedPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
                roundedPanel10.setRoundBottomLeft(5);
                roundedPanel10.setRoundBottomRight(5);
                roundedPanel10.setRoundTopLeft(5);
                roundedPanel10.setRoundTopRight(5);
                roundedPanel10.setLayout(new java.awt.BorderLayout());

                m8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                roundedPanel10.add(m8, java.awt.BorderLayout.CENTER);

                jPanel3.add(roundedPanel10);

                jButton1.setText("You KNOW");

                javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
                roundedPanel1.setLayout(roundedPanel1Layout);
                roundedPanel1Layout.setHorizontalGroup(
                        roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(roundedPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                roundedPanel1Layout.setVerticalGroup(
                        roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addContainerGap(14, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents
    int x = 0;
    int y = 0;
    private void roundedPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel2MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_roundedPanel2MousePressed

    private void roundedPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel2MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_roundedPanel2MouseDragged

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void closeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseEntered
        // TODO add your handling code here:
        closeLabel.setOpaque(true);
        closeLabel.setBackground(Color.gray);
    }//GEN-LAST:event_closeLabelMouseEntered

    private void closeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseExited
        // TODO add your handling code here:
        closeLabel.setBackground(new Color(51, 51, 51));
        closeLabel.setOpaque(false);

    }//GEN-LAST:event_closeLabelMouseExited

    private void miniLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniLabelMouseEntered
        // TODO add your handling code here:
        miniLabel.setOpaque(true);
        miniLabel.setBackground(Color.gray);
    }//GEN-LAST:event_miniLabelMouseEntered

    private void miniLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniLabelMouseExited
        // TODO add your handling code here:

        miniLabel.setBackground(new Color(51, 51, 51));
        miniLabel.setOpaque(false);
    }//GEN-LAST:event_miniLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RagFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RagFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RagFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RagFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                JFrame jf = new RagFrame();
                jf.setVisible(true);

            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel boxLabel;
        private javax.swing.JLabel closeLabel;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JToggleButton jToggleButton1;
        private javax.swing.JLabel m1;
        private javax.swing.JLabel m2;
        private javax.swing.JLabel m3;
        private javax.swing.JLabel m4;
        private javax.swing.JLabel m5;
        private javax.swing.JLabel m6;
        private javax.swing.JLabel m7;
        private javax.swing.JLabel m8;
        private javax.swing.JLabel miniLabel;
        private RoundedPanel roundedPanel1;
        private RoundedPanel roundedPanel10;
        private RoundedPanel roundedPanel2;
        private RoundedPanel roundedPanel3;
        private RoundedPanel roundedPanel4;
        private RoundedPanel roundedPanel5;
        private RoundedPanel roundedPanel6;
        private RoundedPanel roundedPanel7;
        private RoundedPanel roundedPanel8;
        private RoundedPanel roundedPanel9;
        private TableDark tableDark1;
        // End of variables declaration//GEN-END:variables
}
